name: Dependabot Auto Merge

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run universal test
        run: npm run test:universal

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: merge
