name: Dependabot Auto Merge

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

jobs:
  test-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run universal test
        run: npm run test:universal

      - name: Enable auto-merge
        run: gh pr merge "$PR_URL" --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
